apiVersion: v1
kind: Deployment
metadata:
  labels:
    app: du-source-pod
  name: du-source-pod
  namespace: du-poc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: du-source-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: du-source-pod
    spec:
      containers:
      - env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: europe-west2-docker.pkg.dev/du-poc/du-images/source_image_new:latest
        imagePullPolicy: IfNotPresent
        name: source-image-new
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30