apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: du-poc

      # Example configuration for the webserver
      # # at https://github.com/monopole/hello
      # commonLabels:
      #   app: hello
resources:
  - create_namespace.yml
  - du_deployment.yml
  - du_expose.yml
  - ru_deployment.yml
  - ru_expose.yml