apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ru-deployment
  name: ru-deployment
  namespace: du-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ru-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ru-pod
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        imagePullPolicy: IfNotPresent
        name: ru-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: shared-data
          mountPath: /pod_volume

      - name: ru-tcpdump-container
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        imagePullPolicy: IfNotPresent
        command: ["tcpdump" ]
        args: ["-Qin", "-i", "eth0", "-w", "/app/du_captured.pcap"]
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: shared-data
          mountPath: /app
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30   
        
        